# Generated by Django 3.2.25 on 2024-04-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/academies/'),
        ),
        migrations.AlterField(
            model_name='courtimage',
            name='image',
            field=models.ImageField(upload_to='static/images/courts/'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/whitelist/'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='static/whitelist/'),
        ),
    ]
