# Generated by Django 3.2.25 on 2024-04-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourtTool',
        ),
    ]
