# Generated by Django 3.2.25 on 2024-04-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courttool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtfeature',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.court'),
        ),
        migrations.AlterField(
            model_name='courtfeature',
            name='is_free',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='courtfeature',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
