# Generated by Django 3.2.25 on 2024-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240423_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='لا يوجد اسم', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(default='01010101010', max_length=255),
        ),
    ]
