# Generated by Django 3.2.25 on 2024-04-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_verificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='user',
        ),
        migrations.AddField(
            model_name='setting',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile'),
        ),
    ]
