# Generated by Django 3.2.25 on 2024-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240423_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name_ar',
            field=models.CharField(default='لا يوجد اسم', max_length=255, null=True, verbose_name='أسم'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gender',
            field=models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], default='ذكر', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='لا يوجد اسم', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(default='01010101010', max_length=255, null=True),
        ),
    ]
