# Generated by Django 3.2.25 on 2024-05-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city'),
        ),
        migrations.AddField(
            model_name='academy',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AddField(
            model_name='academy',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
