# Generated by Django 3.2.25 on 2024-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240423_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='birth_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='players-birth-certificates/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='id_card_image_of_player',
            field=models.ImageField(blank=True, null=True, upload_to='players-id-cards/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='id_card_image_of_player_parent',
            field=models.ImageField(blank=True, null=True, upload_to='players-parents-id-cards/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='players-passports/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='the_player_image',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='لا يوجد اسم', max_length=255, null=True),
        ),
    ]
