# Generated by Django 3.2.25 on 2024-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240528_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
