# Generated by Django 3.2.25 on 2024-04-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_setting_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile'),
        ),
    ]
