# Generated by Django 3.2.25 on 2024-06-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_academy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
