# Generated by Django 3.2.25 on 2024-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240423_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='managers/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
