# Generated by Django 3.2.25 on 2024-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240413_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
