# Generated by Django 3.2.25 on 2024-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_booktime_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='api.CourtTool'),
        ),
    ]
