# Generated by Django 3.2.25 on 2024-04-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240425_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='championship',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='book',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='court',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='AcademySubscribeRequest',
        ),
        migrations.DeleteModel(
            name='Championship',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
