# Generated by Django 3.2.25 on 2024-04-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20240413_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='event_time',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='is_paied',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='offer_time',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='paied_with',
            field=models.CharField(choices=[('عند الحضور', 'عند الحضور'), ('فودافون كاش', 'فودافون كاش')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='api.CourtTool'),
        ),
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='with_ball',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='BookTime',
        ),
    ]
