# Generated by Django 3.2.25 on 2024-04-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20240415_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
