# Generated by Django 3.2.25 on 2024-04-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_book_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
