# Generated by Django 3.2.25 on 2024-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_book_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pinned_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
