# Generated by Django 3.2.25 on 2024-04-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20240426_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('start_from', models.DateField()),
                ('endt_to', models.DateField()),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('academy_subscribe_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.academysubscribeplan')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile')),
            ],
        ),
    ]
