# Generated by Django 3.2.25 on 2024-04-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_subsribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsribe',
            name='birth_cirtificate',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='father_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='national_id_image1',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='national_id_image2',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='national_id_parent1',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='national_id_parent2',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='player_image',
            field=models.ImageField(blank=True, null=True, upload_to='subscribe/'),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
