# Generated by Django 3.2.25 on 2024-04-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20240426_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsribe',
            name='academy_trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academytrainer'),
        ),
    ]
