# Generated by Django 3.2.25 on 2024-04-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_subsribe_academy_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsribe',
            old_name='endt_to',
            new_name='end_to',
        ),
    ]
