# Generated by Django 3.2.25 on 2024-04-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_endt_to_subsribe_end_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsribe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsribe',
            name='request_from_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='end_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='gender',
            field=models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subsribe',
            name='start_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
