# Generated by Django 3.2.25 on 2024-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20240426_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
