# Generated by Django 3.2.25 on 2024-04-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_book_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='created',
        ),
    ]
