# Generated by Django 3.2.25 on 2024-04-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_created_at_book_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created',
            new_name='created_at',
        ),
    ]
