# Generated by Django 3.2.25 on 2024-04-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20240428_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('trainer', models.CharField(db_index=True, max_length=255, unique=True)),
                ('price_per_class', models.IntegerField(blank=True, default=0, null=True)),
                ('price_per_week', models.IntegerField(blank=True, default=0, null=True)),
                ('price_per_month', models.IntegerField(blank=True, default=0, null=True)),
                ('price_per_year', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.academytype')),
            ],
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
        migrations.DeleteModel(
            name='AcademyTrainer',
        ),
    ]
