# Generated by Django 3.2.25 on 2024-04-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20240428_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
    ]
