# Generated by Django 3.2.25 on 2024-04-18 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedtime',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 20, 21, 1, 377653)),
        ),
    ]
