# Generated by Django 3.2.25 on 2024-04-30 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20240430_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
    ]
