# Generated by Django 3.2.25 on 2024-04-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(upload_to='trainers/'),
        ),
    ]
