# Generated by Django 3.2.25 on 2024-04-18 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20240418_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='court',
        ),
        migrations.AddField(
            model_name='income',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 22, 3, 57, 407726)),
        ),
    ]
