# Generated by Django 3.2.25 on 2024-04-18 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20240418_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 0, 59, 5, 635471)),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
