# Generated by Django 3.2.25 on 2024-04-19 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='academysubscribeplan',
            name='price_per_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academysubscribeplan',
            name='price_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academysubscribeplan',
            name='price_per_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academysubscribeplan',
            name='price_per_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 19, 23, 29, 40, 817350)),
        ),
    ]
