# Generated by Django 3.2.25 on 2024-04-20 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20240420_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='academytrainer',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academytype'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 15, 4, 31, 221745)),
        ),
    ]
