# Generated by Django 3.2.25 on 2024-04-20 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='academytrainer',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.managerprofile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 15, 7, 37, 379052)),
        ),
    ]
