# Generated by Django 3.2.25 on 2024-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='can_academy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='can_courts',
            field=models.BooleanField(default=False),
        ),
    ]
