# Generated by Django 3.2.25 on 2024-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20240421_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='academies/'),
        ),
    ]
